version: "2.4"

services:
  panel:
    image: "pterodactyl-panel"
    restart: unless-stopped
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./data:/data
      - ./config:/config
    #read_only: true
    tmpfs:
      - /tmp
    labels:
      traefik.enable: "true"
      traefik.http.routers.pterodactyl.rule: "Host(`panel.pterodactyl.local`)"
      traefik.http.routers.pterodactyl.tls: "true"
      traefik.http.routers.pterodactyl.tls.certresolver: "le"
      traefik.http.services.pterodactyl.loadbalancer.server.port: 80

  database:
    image: "mariadb:10.6.4"
    restart: unless-stopped
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: "secret123"
      MYSQL_DATABASE: "pterodactyl"
    volumes:
      - database:/var/lib/mysql

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "secret123"]
    volumes:
      - redis:/data

volumes:
  database:
  redis:
